"""Run identity and durable artifact access shared by all entry points."""

import json
import os
import re
from pathlib import Path
from tempfile import NamedTemporaryFile

from .settings import ROOT

RUNS_DIR = Path(os.environ.get("QA_RUNS_DIR", ROOT / "runs")).expanduser().resolve()
INVALID_RUN_ID = "Expected a 32-character lowercase hexadecimal run ID"


def valid_run_id(value: object) -> bool:
    """Accept only identifiers generated by the runner."""
    return isinstance(value, str) and re.fullmatch(r"[0-9a-f]{32}", value) is not None


def run_directory(run_id: str) -> Path:
    """Validate identity and reject run-directory links outside artifact storage."""
    if not valid_run_id(run_id):
        raise ValueError(INVALID_RUN_ID)
    root = RUNS_DIR.resolve()
    folder = root / run_id
    if folder.resolve().parent != root:
        raise ValueError("Run directory escapes artifact storage")
    return folder


def _atomic_write(path: Path, text: str) -> None:
    """Replace a complete file atomically and clean up failed writes."""
    temporary = None
    try:
        with NamedTemporaryFile(
            mode="w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False
        ) as stream:
            temporary = Path(stream.name)
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.replace(path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def save_summary(result: dict) -> None:
    """Write text first and publish the canonical JSON summary last."""
    folder = run_directory(result["run_id"])
    folder.mkdir(parents=True, exist_ok=True)
    _atomic_write(folder / "report.txt", result["report"] + "\n")
    _atomic_write(folder / "summary.json", json.dumps(result, indent=2) + "\n")


def read_summary(run_id: str) -> dict:
    """Read evidence without executing tests or trusting mismatched metadata."""
    path = run_directory(run_id) / "summary.json"
    result = json.loads(path.read_text(encoding="utf-8"))
    if (
        not isinstance(result, dict)
        or result.get("run_id") != run_id
        or not isinstance(result.get("report"), str)
        or result.get("status") not in ("passed", "unsuccessful", "timeout", "launch_error")
    ):
        raise ValueError("Invalid saved summary or mismatched run ID")
    return result
